import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import ChakraProvider from "@/provider/ChakraProvider";
import MainLayout from "@/components/layouts/MainLayout";
import ModalProvider from "@/provider/ModalProvider";
import ReactQueryProvider from "@/provider/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ChakraProvider>
            <ReactQueryProvider>
              <ModalProvider />
              <MainLayout>{children}</MainLayout>
            </ReactQueryProvider>
          </ChakraProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
